import type { Project } from "./types";

const now = new Date();
const daysAgo = (n: number) => new Date(now.getTime() - n * 86400000).toISOString();
const daysAhead = (n: number) => {
  const d = new Date(now.getTime() + n * 86400000);
  return d.toISOString().slice(0, 10);
};

export const SEED_PROJECTS: Project[] = [
  {
    id: "prj_xprimeray",
    title: "xPRIMEray Rendering Engine",
    short_summary: "Custom GPU-first physically based renderer with experimental spectral pipeline.",
    full_description:
      "A from-scratch rendering engine focused on real-time spectral light transport, importance-sampled BRDFs and a node-based material graph. Targets WebGPU first, with a Vulkan backend planned. Goal: ship a public alpha that can render the reference scenes within 16ms on a 4070-class GPU.",
    category: "Engineering",
    status: "Building",
    priority: "Critical",
    progress_percent: 42,
    confidence_level: "High",
    next_action: "Wire up multi-bounce GI accumulation and benchmark against Sponza scene.",
    github_repo_url: "https://github.com/xprime/xprimeray",
    evidence_links: [
      { id: "e1", label: "Spectral pipeline design doc", url: "https://example.com/spec" },
      { id: "e2", label: "First-light render", url: "https://example.com/render" },
    ],
    tags: ["wgpu", "rendering", "graphics", "rust"],
    milestone_date: daysAhead(28),
    notes: "Need to revisit BVH refit cost vs. rebuild. Current frame budget breaks above 1.2M tris.",
    created_at: daysAgo(64),
    updated_at: daysAgo(1),
  },
  {
    id: "prj_wormhole",
    title: "Wormhole Portal Validation",
    short_summary: "Tabletop analog experiments probing traversable geometry assumptions.",
    full_description:
      "Series of analog gravity experiments using BEC condensates and acoustic horizons to probe boundary conditions of traversable wormhole geometries. Currently characterizing noise floor of the interferometer rig before second-pass measurements.",
    category: "Physics Experiment",
    status: "Validating",
    priority: "High",
    progress_percent: 28,
    confidence_level: "Medium",
    next_action: "Recalibrate interferometer arm; collect 24h baseline noise dataset.",
    github_repo_url: "",
    evidence_links: [
      { id: "e1", label: "Run #14 dataset", url: "https://example.com/run14" },
    ],
    tags: ["physics", "analog-gravity", "experiment"],
    milestone_date: daysAhead(42),
    notes: "Vibration isolation is the dominant noise source. Consider Minus-K stage upgrade.",
    created_at: daysAgo(120),
    updated_at: daysAgo(3),
  },
  {
    id: "prj_act_episode",
    title: "ACT Episode 07 — Mythology Arc",
    short_summary: "Long-form video on the founding myth and the lab's narrative thread.",
    full_description:
      "Episode 07 closes the first season's mythology arc. Outline locked, B-roll storyboard in progress, and three interview segments to capture. Targeting 22-minute runtime with the new color grade preset.",
    category: "Content",
    status: "Researching",
    priority: "Medium",
    progress_percent: 18,
    confidence_level: "High",
    next_action: "Lock final outline and ship interview brief to guest #2.",
    github_repo_url: "",
    evidence_links: [
      { id: "e1", label: "Outline v3", url: "https://example.com/outline" },
    ],
    tags: ["video", "narrative", "season-1"],
    milestone_date: daysAhead(21),
    notes: "Need a stronger cold open. Current draft buries the lede.",
    created_at: daysAgo(20),
    updated_at: daysAgo(2),
  },
  {
    id: "prj_portal_site",
    title: "Public Research Portal",
    short_summary: "Landing page + public notebook for the lab's research and releases.",
    full_description:
      "A clean, fast public portal for the lab. Hero, current research log, project index, episode archive, and a pared-down 'now' page. Should feel like a research site, not a marketing page.",
    category: "Product Concept",
    status: "Ready to Launch",
    priority: "High",
    progress_percent: 88,
    confidence_level: "High",
    next_action: "Final QA pass on mobile + push to production.",
    github_repo_url: "https://github.com/xprime/portal",
    evidence_links: [
      { id: "e1", label: "Staging preview", url: "https://staging.example.com" },
      { id: "e2", label: "Lighthouse report", url: "https://example.com/lh" },
    ],
    tags: ["web", "public", "portfolio"],
    milestone_date: daysAhead(5),
    notes: "Hold launch until Episode 07 is queued so the homepage has a fresh hero.",
    created_at: daysAgo(45),
    updated_at: daysAgo(0.2),
  },
  {
    id: "prj_blender_lab",
    title: "Blender + xPRIME Visual Demo Lab",
    short_summary: "Cinematic scene library bridging Blender and the xPRIMEray pipeline.",
    full_description:
      "A curated set of Blender scenes that round-trip through xPRIMEray for spectral renders, comparison shots, and motion tests. Doubles as a regression suite for the renderer and a B-roll source for episodes.",
    category: "Content",
    status: "Building",
    priority: "Medium",
    progress_percent: 36,
    confidence_level: "High",
    next_action: "Finalize the 'lensing corridor' scene and export USD with spectral materials.",
    github_repo_url: "",
    evidence_links: [
      { id: "e1", label: "Scene index", url: "https://example.com/scenes" },
    ],
    tags: ["blender", "usd", "demo", "render"],
    milestone_date: daysAhead(18),
    notes: "Keep every scene under 90s render at preview quality so iteration stays fast.",
    created_at: daysAgo(34),
    updated_at: daysAgo(2),
  },
  {
    id: "prj_curved_optics",
    title: "Curved-Ray Optics Experiment Tracker",
    short_summary: "Logbook for tabletop experiments bending light along engineered gradients.",
    full_description:
      "Tracks the run-by-run setup, parameters, and results of curved-ray optics experiments using GRIN media and structured light. Each entry pairs a setup photo, a measured trajectory, and a simulation overlay rendered in xPRIMEray.",
    category: "Physics Experiment",
    status: "Validating",
    priority: "High",
    progress_percent: 47,
    confidence_level: "Medium",
    next_action: "Capture run #22 with the new collimator and compare against the spectral sim.",
    github_repo_url: "",
    evidence_links: [
      { id: "e1", label: "Run #21 trajectory plot", url: "https://example.com/run21" },
    ],
    tags: ["optics", "experiment", "grin", "lensing"],
    milestone_date: daysAhead(33),
    notes: "Stray reflections off the cell wall are still polluting the long tail.",
    created_at: daysAgo(58),
    updated_at: daysAgo(1),
  },
  {
    id: "prj_rabbit_hole",
    title: "Rabbit-Hole Short Film / Trailer Board",
    short_summary: "Pre-production board for the Rabbit-Hole short film and teaser trailer.",
    full_description:
      "Beat sheet, shotlist, lookdev frames, and music cues for the Rabbit-Hole short. Trailer cut targets festival submission window; full short follows as a season finale companion piece.",
    category: "Content",
    status: "Researching",
    priority: "High",
    progress_percent: 22,
    confidence_level: "Medium",
    next_action: "Lock the opening descent sequence and previz it in Blender.",
    github_repo_url: "",
    evidence_links: [
      { id: "e1", label: "Lookdev board", url: "https://example.com/lookdev" },
    ],
    tags: ["film", "trailer", "previz", "narrative"],
    milestone_date: daysAhead(54),
    notes: "Trailer should stand alone — no reliance on the full short for context.",
    created_at: daysAgo(26),
    updated_at: daysAgo(4),
  },
  {
    id: "prj_soundtrack",
    title: "Playlist / Soundtrack Experiment Board",
    short_summary: "Working board for episode soundtracks and ambient research playlists.",
    full_description:
      "A living board of soundtrack experiments: per-episode cue lists, ambient research playlists, and short scoring sketches. Tracks which cues survived to picture lock and which got cut.",
    category: "Content",
    status: "Backlog",
    priority: "Low",
    progress_percent: 12,
    confidence_level: "Medium",
    next_action: "Draft the ambient cue palette for Episode 07 cold open.",
    github_repo_url: "",
    evidence_links: [],
    tags: ["audio", "score", "playlist"],
    milestone_date: daysAhead(40),
    notes: "Keep a 'rejected cues' lane — half end up reused two episodes later.",
    created_at: daysAgo(18),
    updated_at: daysAgo(6),
  },
];
