import type { Edge, Node } from "./types"

export const hydrogenNodes: Node[] = [
  {
    id: "hydrogen",
    stratum: "trunk",
    epistemic: "observed",
    title: "Hydrogen",
    claim: "One proton and one electron. The object these nodes are about.",
  },
  {
    id: "obs-stable",
    stratum: "trunk",
    epistemic: "observed",
    title: "Observed stability",
    claim: "Bound hydrogen does not collapse on a 10⁻¹¹ s timescale.",
  },
  {
    id: "e1",
    stratum: "trunk",
    epistemic: "calculated",
    title: "E₁",
    claim:
      "Schrödinger–Coulomb eigenvalue. Reduced mass is a toggle, not a new theory.",
    source: "Schrödinger, Ann. Phys. 79, 361 (1926); CODATA 2022",
  },
  {
    id: "psi",
    stratum: "trunk",
    epistemic: "calculated",
    title: "ψ₁₀₀",
    claim: "Stationary 1s eigenfunction. The density does not evolve. There is no trajectory.",
    source: "Schrödinger, Ann. Phys. 79, 361 (1926)",
    year: 1926,
  },
  {
    id: "pr",
    stratum: "trunk",
    epistemic: "calculated",
    title: "P(r)",
    claim: "Plotted function 4πr²|ψ|². The probability reading is a separate node.",
  },
  {
    id: "rutherford",
    stratum: "root",
    epistemic: "observed",
    title: "Compact nucleus",
    claim: "Scattering requires a compact positive nucleus, not a diffuse sphere.",
    source: "Rutherford, Phil. Mag. 21, 669 (1911)",
    year: 1911,
  },
  {
    id: "larmor",
    stratum: "root",
    epistemic: "calculated",
    title: "Larmor power",
    claim: "A nonrelativistic accelerating charge radiates P = e²a²/(6πε₀c³).",
  },
  {
    id: "classical-orbit",
    stratum: "root",
    epistemic: "calculated",
    title: "Circular Bohr orbit",
    claim:
      "Point nucleus, circular orbit at a₀, v = αc. An assumption of the collapse estimate, not a measurement.",
    source: "Bohr, Phil. Mag. 26, 1 (1913)",
    year: 1913,
  },
  {
    id: "collapse-tau",
    stratum: "root",
    epistemic: "calculated",
    title: "Collapse time",
    claim:
      "τ = |E|/P = 3a₀/(4α⁴c) under the energy-loss approximation. Not Abraham–Lorentz.",
  },
  {
    id: "schrodinger",
    stratum: "root",
    epistemic: "calculated",
    title: "Schrödinger equation",
    claim: "Time-independent Coulomb problem. Yields ψ₁₀₀ and E₁. Does not by itself say probability.",
    source: "Schrödinger, Ann. Phys. 79, 361 (1926)",
    year: 1926,
  },
  {
    id: "codata",
    stratum: "root",
    epistemic: "observed",
    title: "CODATA 2022",
    claim: "Pinned recommended constants. This screen does not refit them.",
    source: "Mohr, Newell, Taylor, Tiesinga, Rev. Mod. Phys. 97, 025002 (2025)",
    year: 2022,
  },
  {
    id: "born-rule",
    stratum: "branch",
    epistemic: "interpreted",
    register: "physical_correspondence",
    title: "Born rule",
    claim: "Reads |ψ|² as probability. That reading is not a line of the differential equation.",
    source: "Born, Z. Phys. 37, 863 (1926)",
    year: 1926,
  },
  {
    id: "planetary-picture",
    stratum: "branch",
    epistemic: "interpreted",
    register: "historical_influence",
    title: "Planetary picture",
    claim: "The electron as a small body on a Kepler orbit. Shown only as the model that fails.",
  },
  {
    id: "cloud-picture",
    stratum: "branch",
    epistemic: "interpreted",
    register: "physical_correspondence",
    title: "Cloud picture",
    claim: "A popular picture of the radial density. It does not derive the eigenvalue.",
  },
  {
    id: "uncertainty-heuristic",
    stratum: "branch",
    epistemic: "interpreted",
    register: "physical_correspondence",
    title: "Uncertainty estimate",
    claim: "A δx δp estimate puts a minimum near a₀. It does not replace the eigenvalue.",
  },
  {
    id: "gaussian-trial",
    stratum: "root",
    epistemic: "calculated",
    title: "Gaussian trial",
    claim:
      "Normalized family ψ_λ = (πλ²)^(−3/4) exp(−r²/(2λ²)). Coulomb expectation on that family only. The minimum is an upper bound and is not E₁.",
  },
  {
    id: "puthoff-1987",
    stratum: "root",
    epistemic: "calculated",
    title: "Puthoff 1987",
    year: 1987,
    claim:
      "Circular orbit. Absorbed power (18) set equal to radiated power (19) gives m ω₀ r₀² = ℏ (20). Competes with the Schrödinger account. Does not derive ψ₁₀₀ or E₁.",
    source: "Puthoff, Phys. Rev. D 35, 3266 (1987)",
  },
  {
    id: "h-seam-1",
    stratum: "seam",
    epistemic: "hypothesized",
    title: "H-SEAM-1",
    claim:
      "Can one vacuum-based mechanism derive both the hydrogen ground-state structure and radiative corrections without inserting the quantum result?",
  },
]

export const hydrogenEdges: Edge[] = [
  {
    id: "tau-from-larmor",
    from: "collapse-tau",
    to: "larmor",
    relation: "derives_from",
    epistemic: "calculated",
    note: "The time is |E| divided by the Larmor power.",
  },
  {
    id: "tau-from-orbit",
    from: "collapse-tau",
    to: "classical-orbit",
    relation: "derives_from",
    epistemic: "calculated",
    note: "Evaluated on the circular a₀ orbit.",
  },
  {
    id: "tau-from-codata",
    from: "collapse-tau",
    to: "codata",
    relation: "derives_from",
    epistemic: "calculated",
    note: "α, a₀, and c are pinned inputs.",
  },
  {
    id: "tau-competes-stability",
    from: "collapse-tau",
    to: "obs-stable",
    relation: "competes_with",
    epistemic: "calculated",
    note: "The orbit model predicts collapse. Hydrogen is observed not to.",
  },
  {
    id: "e1-from-schrodinger",
    from: "e1",
    to: "schrodinger",
    relation: "derives_from",
    epistemic: "calculated",
    note: "Eigenvalue of the Coulomb problem.",
  },
  {
    id: "e1-from-codata",
    from: "e1",
    to: "codata",
    relation: "derives_from",
    epistemic: "calculated",
    note: "E₁ = −(μ/mₑ) hcR∞.",
  },
  {
    id: "psi-from-schrodinger",
    from: "psi",
    to: "schrodinger",
    relation: "derives_from",
    epistemic: "calculated",
    note: "Ground eigenfunction.",
  },
  {
    id: "pr-from-psi",
    from: "pr",
    to: "psi",
    relation: "derives_from",
    epistemic: "calculated",
    note: "The plotted function is 4πr²|ψ|². Probability is not this edge.",
  },
  {
    id: "pr-from-codata",
    from: "pr",
    to: "codata",
    relation: "derives_from",
    epistemic: "calculated",
    note: "The radial scale is a₀ or a_μ.",
  },
  {
    id: "born-interprets-pr",
    from: "born-rule",
    to: "pr",
    relation: "interprets",
    epistemic: "interpreted",
    note: "The curve is read as a radial probability.",
  },
  {
    id: "planet-inspired-by-nucleus",
    from: "planetary-picture",
    to: "rutherford",
    relation: "inspired_by",
    epistemic: "interpreted",
    note: "A nucleus suggests a center. It does not imply a planet.",
  },
  {
    id: "planet-interprets-orbit",
    from: "planetary-picture",
    to: "classical-orbit",
    relation: "interprets",
    epistemic: "interpreted",
    note: "The bead on the spiral is this picture, not the 1s state.",
  },
  {
    id: "cloud-interprets-pr",
    from: "cloud-picture",
    to: "pr",
    relation: "interprets",
    epistemic: "interpreted",
    note: "A picture of the density. Not a derivation of E₁.",
  },
  {
    id: "uncertainty-interprets-e1",
    from: "uncertainty-heuristic",
    to: "e1",
    relation: "interprets",
    epistemic: "interpreted",
    note: "Scale estimate beside the eigenvalue, not instead of it.",
  },
  {
    id: "gaussian-from-schrodinger",
    from: "gaussian-trial",
    to: "schrodinger",
    relation: "derives_from",
    epistemic: "calculated",
    note: "Expectation value of the Coulomb Hamiltonian. The trial is not an eigenfunction.",
  },
  {
    id: "gaussian-from-codata",
    from: "gaussian-trial",
    to: "codata",
    relation: "derives_from",
    epistemic: "calculated",
    note: "μ and the Rydberg energy set the unit. They are not adjusted to force the minimum onto E₁.",
  },
  {
    id: "gaussian-approximates-e1",
    from: "gaussian-trial",
    to: "e1",
    relation: "approximates",
    epistemic: "calculated",
    note: "Upper bound of this restricted family: −(8/(3π)) of the binding. Not a derivation of the eigenvalue.",
  },
  {
    id: "puthoff-from-larmor",
    from: "puthoff-1987",
    to: "larmor",
    relation: "derives_from",
    epistemic: "calculated",
    note: "Radiated term is the Larmor power on the circular orbit, Puthoff (19).",
  },
  {
    id: "puthoff-from-orbit",
    from: "puthoff-1987",
    to: "classical-orbit",
    relation: "derives_from",
    epistemic: "calculated",
    note: "The orbit is the Bohr-level circle, two oscillators in quadrature, Puthoff (17).",
  },
  {
    id: "puthoff-competes-schrodinger",
    from: "puthoff-1987",
    to: "schrodinger",
    relation: "competes_with",
    epistemic: "calculated",
    note: "Same observed atom. This balance does not derive ψ₁₀₀ or E₁.",
  },
  {
    id: "puthoff-competes-collapse",
    from: "puthoff-1987",
    to: "collapse-tau",
    relation: "competes_with",
    epistemic: "calculated",
    note: "Collapse counts only emission. Puthoff adds absorption and looks for a balance.",
  },
]

/** Not part of the accepted graph. The screen shows the validator rejecting it. */
export const rejectedResonance: Edge = {
  id: "fixture-resonate-e1",
  from: "cloud-picture",
  to: "e1",
  relation: "resonates_with",
  epistemic: "interpreted",
  note: "Deliberate invalid edge. A picture must not resonate into the eigenvalue.",
}
