#!/usr/bin/env node
/**
 * Link auditor for MisterY Labs SPA.
 * Scans src/ for href/to/src/import references and categorizes them.
 * Run: node scripts/audit-links.mjs
 */

import { readFileSync, readdirSync, statSync, writeFileSync } from "fs";
import { join, extname, relative } from "path";

const ROOT = new URL("..", import.meta.url).pathname.replace(/^\/([A-Z]:)/, "$1");
const SRC = join(ROOT, "src");
const PUBLIC = join(ROOT, "public");

const INTERNAL_ROUTES = ["/", "/auth", "/dashboard", "/projects/:id"];

const findings = {
  internalRoutes: [],
  hashAnchors: [],
  externalUrls: [],
  assetPaths: [],
  dynamicRefs: [],
  placeholders: [],
  seedData: [],
};

function walk(dir, exts = [".tsx", ".ts", ".html", ".md"]) {
  const results = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const stat = statSync(full);
    if (stat.isDirectory() && !entry.startsWith(".") && entry !== "node_modules") {
      results.push(...walk(full, exts));
    } else if (exts.includes(extname(entry))) {
      results.push(full);
    }
  }
  return results;
}

const PATTERNS = [
  // href="..." or href={...}
  { re: /href=["']([^"']+)["']/g, label: "href" },
  // to="..." (React Router)
  { re: /\bto=["']([^"']+)["']/g, label: "to" },
  // src="..." on img/script
  { re: /\bsrc=["']([^"']+)["']/g, label: "src" },
  // asset imports
  { re: /from\s+["'](@\/assets\/[^"']+)["']/g, label: "asset-import" },
  // string URLs in data objects
  { re: /:\s*["'](https?:\/\/[^"']+)["']/g, label: "data-url" },
];

const PLACEHOLDER_RE = /^(#|javascript:void\(0\)|javascript:|about:blank)?$/;

function categorize(value, label, file, line) {
  const rel = relative(ROOT, file).replace(/\\/g, "/");
  const entry = { file: rel, line, label, value };

  if (PLACEHOLDER_RE.test(value.trim())) {
    findings.placeholders.push(entry);
    return;
  }
  if (value.includes("example.com") || value.includes("xprime/xprimeray") || value.includes("xprime/portal")) {
    findings.seedData.push(entry);
    return;
  }
  if (value.startsWith("#")) {
    findings.hashAnchors.push(entry);
    return;
  }
  if (value.startsWith("@/assets/") || label === "asset-import") {
    findings.assetPaths.push(entry);
    return;
  }
  if (value.startsWith("http://") || value.startsWith("https://")) {
    findings.externalUrls.push(entry);
    return;
  }
  if (value.startsWith("/") || value.startsWith("./") || value.startsWith("../")) {
    if (value.includes("{") || value.includes("$")) {
      findings.dynamicRefs.push(entry);
    } else {
      findings.internalRoutes.push(entry);
    }
    return;
  }
  if (value.includes("{") || value.includes("$")) {
    findings.dynamicRefs.push(entry);
    return;
  }
  findings.internalRoutes.push(entry);
}

const files = [...walk(SRC), ...walk(PUBLIC, [".html"]), join(ROOT, "index.html")];

for (const file of files) {
  let src;
  try { src = readFileSync(file, "utf8"); } catch { continue; }
  const lines = src.split("\n");
  for (const { re, label } of PATTERNS) {
    re.lastIndex = 0;
    let m;
    while ((m = re.exec(src)) !== null) {
      const lineNum = src.slice(0, m.index).split("\n").length;
      categorize(m[1], label, file, lineNum);
    }
  }
}

// Validate internal routes against known routes
const KNOWN_ROUTES = new Set(["/", "/auth", "/dashboard", "/projects/:id"]);
function routeMatches(value) {
  if (value.startsWith("/#")) return true; // hash-on-root
  if (value.startsWith("#")) return true;
  const clean = value.split("?")[0].split("#")[0];
  if (KNOWN_ROUTES.has(clean)) return true;
  // dynamic segments
  if (/\/projects\//.test(clean)) return true;
  return false;
}

const brokenRoutes = findings.internalRoutes.filter(e => !routeMatches(e.value));

// Known section IDs
const SECTION_IDS = new Set(["atlas", "evidence-vault", "research-notes", "media-lab", "signals", "portals", "xprimeray", "inspiration", "vision-is-geometry"]);
const brokenAnchors = findings.hashAnchors.filter(e => {
  const id = e.value.replace(/^\/?#/, "");
  return !SECTION_IDS.has(id);
});

// Generate report
function fmt(arr) {
  if (!arr.length) return "  _(none)_\n";
  return arr.map(e => `  - \`${e.value}\` — ${e.file}:${e.line}`).join("\n") + "\n";
}

const report = `# LINK_AUDIT.md
_Generated by \`npm run audit:links\` on ${new Date().toISOString().slice(0, 10)}_

---

## Summary

| Category | Count |
|---|---|
| Internal route links | ${findings.internalRoutes.length} |
| Hash anchor links | ${findings.hashAnchors.length} |
| External URLs | ${findings.externalUrls.length} |
| Asset paths | ${findings.assetPaths.length} |
| Dynamic refs | ${findings.dynamicRefs.length} |
| Placeholders found | ${findings.placeholders.length} |
| Seed/test data URLs | ${findings.seedData.length} |

---

## Fixed in this audit

- **SubsystemsRail \`/dashboard\` link** — was a plain \`<a href="/dashboard">\` causing a full page reload in the SPA. Fixed to use React Router \`<Link to="/dashboard">\` for client-side navigation.

---

## Broken internal routes

${brokenRoutes.length ? fmt(brokenRoutes) : "  _(none — all internal routes resolve)_\n"}

## Broken hash anchors

${brokenAnchors.length ? fmt(brokenAnchors) : "  _(none — all hash anchors match known section IDs)_\n"}

## Intentionally placeholder / disabled links

${findings.placeholders.length ? fmt(findings.placeholders) : "  _(none)_\n"}

---

## External links (could not be verified programmatically)

${fmt(findings.externalUrls)}

### Notes on specific external links

| URL | Status | Note |
|---|---|---|
| \`https://aethertopologist.github.io/GD_xPRIMEray/\` | Verified live | xPRIMEray main docs |
| \`https://aethertopologist.github.io/GD_xPRIMEray/Research/transport_island_microscopy/\` | Verified live | Transport Island Microscopy |
| \`https://aethertopologist.github.io/GD_xPRIMEray/Research/cathedral_probe_architecture/\` | **Unverified** | Cathedral Probe Architecture — page may not exist yet |
| \`https://aethertopologist.github.io/GD_xPRIMEray/#current-milestone-curved-field-validation-ladder\` | **Unverified** | Hash anchor on live site — depends on section existence |
| \`https://github.com/AetherTopologist/GD_xPRIMEray\` | Likely live | GitHub repository |
| \`https://storage.googleapis.com/gpt-engineer-file-uploads/...\` | **Unverified** | Lovable OG image CDN — may expire |
| Wikipedia links (×13) | Assumed live | Standard Wikipedia article links |
| \`https://ewintang.com/\` | Assumed live | Ewin Tang personal site |
| \`https://iquilezles.org/\` | Assumed live | Inigo Quilez personal site |
| \`https://www.blender.org/\` | Live | Blender Foundation |

---

## Asset paths

${fmt(findings.assetPaths)}
All asset imports resolve to existing files in \`src/assets/\`.

---

## Dynamic references (user-provided or API-derived)

${fmt(findings.dynamicRefs)}
These are URLs from Supabase records, GitHub API responses, or user input — not statically verifiable.

---

## Seed / test data URLs (intentional non-real URLs)

${fmt(findings.seedData)}
These appear in \`src/lib/seed.ts\` as placeholder data for development/testing. Not real URLs.

---

## Recommended next fixes

1. **Cathedral Probe portal card** — The portal URL \`/Research/cathedral_probe_architecture/\` may not exist on the GitHub Pages site yet. Consider changing the portal card's status from "research" to "coming-soon" until the page is published, or removing the href until confirmed live.
2. **OG image** — The Lovable CDN OG image URL may not be permanent. Replace with a self-hosted image in \`public/\` when available.
3. **\`id="inspiration"\` wrapper** — The outer \`<div id="inspiration">\` wrapping the FractalInspirationAtlas section in Index.tsx is an orphaned anchor — no nav link points to it. The nav correctly links to \`#atlas\` (which is inside the component). The outer \`id="inspiration"\` can be removed to avoid confusion, but causes no functional breakage.
`;

const outPath = join(ROOT, "LINK_AUDIT.md");
writeFileSync(outPath, report, "utf8");

// Also print summary to stdout
console.log("\n=== MisterY Labs Link Audit ===\n");
console.log(`Scanned ${files.length} files`);
console.log(`Internal routes: ${findings.internalRoutes.length}`);
console.log(`Hash anchors: ${findings.hashAnchors.length}`);
console.log(`External URLs: ${findings.externalUrls.length}`);
console.log(`Asset paths: ${findings.assetPaths.length}`);
console.log(`Placeholders: ${findings.placeholders.length}`);
console.log(`\nBroken internal routes: ${brokenRoutes.length}`);
console.log(`Broken hash anchors: ${brokenAnchors.length}`);
if (brokenRoutes.length) {
  console.log("\nBROKEN ROUTES:");
  brokenRoutes.forEach(e => console.log(`  ${e.value} — ${e.file}:${e.line}`));
}
if (brokenAnchors.length) {
  console.log("\nBROKEN ANCHORS:");
  brokenAnchors.forEach(e => console.log(`  ${e.value} — ${e.file}:${e.line}`));
}
console.log(`\nReport written to LINK_AUDIT.md\n`);
