// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Defensive initialization: prevents "supabaseUrl is required" crash when env vars are missing
// (common in local dev without .env or in some preview builds).
// Components that need Supabase should check if (supabase) before use, or use static fallbacks.
let supabaseClient: ReturnType<typeof createClient<Database>> | null = null;

if (SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY) {
  supabaseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: 'pkce',
    }
  });
} else {
  console.warn(
    "[Supabase] VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY is missing. " +
    "Supabase features (auth, functions, realtime) are disabled. Using static/mock data where applicable."
  );
}

export const supabase = supabaseClient;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";